before:
  hooks:
    - go install github.com/rakyll/statik
    - sh -x ./fe.sh
    # You may remove this if you don't use go modules.
    - go mod tidy
    

snapshot:
  name_template: '{{ .Tag }}'
checksum:
  name_template: 'checksums.txt'
changelog:

builds:
  - id: build
    hooks:
      pre:
      - cmd: sh -x ./fe.sh
        output: true
    main: ./cmd/center/
    binary: n9e
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/ccfos/nightingale/v6/pkg/version.Version={{ .Tag }}-{{.Commit}}
  - id: build-cli
    main: ./cmd/cli/
    binary: n9e-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/ccfos/nightingale/v6/pkg/version.Version={{ .Tag }}-{{.Commit}}
  - id: build-edge
    main: ./cmd/edge/
    binary: n9e-edge
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/ccfos/nightingale/v6/pkg/version.Version={{ .Tag }}-{{.Commit}}

archives:
  - id: n9e
    builds:
      - build
      - build-cli
      - build-edge
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "stellar-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: false
    files:
      - docker/*
      - etc/*
      - integrations/*
      - cli/*
      - n9e.sql

release:
  github:
    owner: caapap
    name: nightingale
  name_template: "v{{ .Version }}"
  draft: false
  replace_existing_artifacts: true
  mode: replace

dockers:
  - image_templates:
      - swr.cn-east-3.myhuaweicloud.com/caapap/stellar:v{{ .Version }}-amd64
    goos: linux
    goarch: amd64
    ids:
      - build
    dockerfile: docker/Dockerfile.goreleaser
    extra_files:
      - etc
      - integrations
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - swr.cn-east-3.myhuaweicloud.com/caapap/stellar:v{{ .Version }}-arm64v8
    goos: linux
    goarch: arm64
    ids:
      - build
    dockerfile: docker/Dockerfile.goreleaser.arm64
    extra_files:
      - etc
      - integrations
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64/v8"

docker_manifests:

  - name_template: swr.cn-east-3.myhuaweicloud.com/caapap/stellar:v{{ .Version }}
    image_templates:
      - swr.cn-east-3.myhuaweicloud.com/caapap/stellar:v{{ .Version }}-amd64
      - swr.cn-east-3.myhuaweicloud.com/caapap/stellar:v{{ .Version }}-arm64v8

  - name_template: swr.cn-east-3.myhuaweicloud.com/caapap/stellar:latest
    image_templates:
      - swr.cn-east-3.myhuaweicloud.com/caapap/stellar:v{{ .Version }}-amd64
      - swr.cn-east-3.myhuaweicloud.com/caapap/stellar:v{{ .Version }}-arm64v8